name: Correction events exo

on:
  push: 
    branches:
      - dev 
  # 1.3
  #push:
  # branches: 
  #- "!staging"

  # 1.4
  #push:
  # branches:
  # - 'feat/**'

  # 1.5
  # push:
  # paths:
  # - '**.ts'
  
  #1.6
  # push:
  #   paths:
  #     - node-app

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3